[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true

[tool.ruff]
line-length = 120
per-file-ignores = {"yq/__init__.py" = ["F401"]}

[tool.mypy]
files = [
  "yq"
]
check_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "argcomplete.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tomlkit.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "yq.version"
ignore_missing_imports = true

[tool.setuptools_scm]
version_file = "yq/version.py"
